### ISSUE TITLE
Declaration Variable

### ISSUE THREAD

**Issue by PatrikRindlisbacher** [SMFSW/SeqButton#3]
Hi 
Thank You 
verry easy and good library

I found e Issue

holdDone    is declared as   **uint8_t**	  in SeqButton_h

used is only as   **boolean**

**Comment by SMFSW** [comment]
Thanks, I'm glad you like this library.

`holdDone`, `pusDone `& `relDone `are declared as bits (`:1`) on a `uint8_t`, the bits are packed on a `uint8_t `variable. This ends up being more or less the same as if I declared them as `bool`.
Even if I declared `uint8_t `for these, it would be less optimized in terms of RAM use, but this would still work as expected.

**Comment by PatrikRindlisbacher** [comment]
[scr.zip](https://github.com/SMFSW/SeqButton/files/2476573/scr.zip)

Thank you very much
I adjusted the project so that there is also a filter for releasing the button.

**Comment by PatrikRindlisbacher** [comment]
Dank You
